---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- lib/generators/wechat/templates/app/controllers/wechats_controller.rb
- spec/**/*
