AllCops:
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 63

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Style/NumericLiterals:
  MinDigits: 7
