AllCops:
  Include:
  - 'lib/**/*.rb'
  Exclude:
  - 'bin/**/*'
  - 'vendor/**/*'
  - 'spec/**/*.rb'
  - 'lib/generators/wechat/templates/app/controllers/wechats_controller.rb'
  NewCops: enable
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 180

Metrics/AbcSize:
  Max: 68

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/MethodLength:
  Max: 40

Metrics/ParameterLists:
  Max: 8

Style/NumericLiterals:
  MinDigits: 7

Metrics/PerceivedComplexity:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 22

Style/AsciiComments:
  Enabled: false

Metrics/BlockNesting:
  Max: 4
